spring.application.name=native-demo
demo.greeting-plugin=com.example.nativedemo.greeting.reflective.FriendlyGreetingPlugin
demo.greeting-resource=greetings/resource-greeting.txt
demo.greeting-proxy-interface=com.example.nativedemo.greeting.proxy.ProxyGreeting
